# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: 'MyAgentPool'

steps:
- task: Bash@3
  displayName: 'Workaround: Set environment variables manually'
  inputs:
      targetType: 'inline'
      script: |
        cd ~
        echo "##vso[task.setvariable variable=HOME]$(pwd)"
        echo "##vso[task.setvariable variable=USER]$(whoami)"
        echo "##vso[task.setvariable variable=JAVA_HOME_8_X64]/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64"
        echo "##vso[task.setvariable variable=JAVA_HOME_11_X64]/usr/lib/jvm/adoptopenjdk-11-hotspot-amd64"
        echo "##vso[task.setvariable variable=JAVA_HOME]/usr/lib/jvm/adoptopenjdk-11-hotspot-amd64"
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

